openapi: 3.0.1
info:
  title: Answering ck3 questions
  description: An API that allows users to ask questions and get answers from a crusader kings database.
  version: 'v1'
servers:
  - url: http://localhost:5003
paths:
  /ck/{question}:
    get:
      operationId: getAnswer
      summary: Get the answer to a ck3 related question
      parameters:
      - in: path
        name: question
        schema:
            type: string
        required: true
        description: The question to be answered.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAnswerResponse'
components:
  schemas:
    getAnswerResponse:
      type: object
      properties:
        answer:
          type: string
          description: The answer to the question.
